### ISSUE TITLE
docker-compose from github or docker pull ?

### ISSUE THREAD

**Issue by dotMastaz** [devgeniem/docker-alpine-wordpress#2]
Hello,

I'm newbie...
How to use your container ?
With docker-composer with files in github ou docker pull ?
I try with docker pull :
$ docker pull devgeniem/alpine-wordpress
And when i "docker run ..." i have many errors about missing directory /data/code,...

Any help !
Thank you !!

**Comment by onnimonni** [comment]
Sorry for not noticing this issue for so long time. This image is only runtime for Wordpress and you have to include it into the /data/project path. I think you have already moved on after so many months but please reopen the issue if something comes up.
